### ISSUE TITLE
Thanks for your work! I am interested in your proposed RaBitQ and Extended RaBitQ. But I have a question that I didn't find the normalization operation in your code，both RaBitQ and Extended RaBitQ. And in this repo,  I have seen `python/utils/preprocess.py` which is consist of normalization. But I don't see code using this function in the follow-up process. I'm too confused about this. Thank you!  $$ o:=\frac{o_{r}-c}{||o_{r}-c||}, q:=\frac{q_{r}-c}{||q_{r}-c||} $$

### ISSUE THREAD

**Issue by Godzilla0517** [gaoj0017/RaBitQ#7] opened 2024-11-20 02:25 UTC
Thanks for your work! I am interested in your proposed RaBitQ and Extended RaBitQ. But I have a question that I didn't find the normalization operation in your code，both RaBitQ and Extended RaBitQ. And in repo of Extended RaBitQ ,  I have seen `python/utils/preprocess.py` which is consist of normalization. But I don't see code using this function in the follow-up process. I'm too confused about this. Thank you!

$$
o:=\frac{o_{r}-c}{||o_{r}-c||}, q:=\frac{q_{r}-c}{||q_{r}-c||}
$$

**Comment by gaoj0017** [comment] 2024-11-20 02:27
The normalization step is not explicitly reflected in the index phase.

Let us assume that we are computing the quantization code for a vector.

In RaBitQ, the code is computed by checking the signs of each dimension. Clearly, the result is unchanged whether or not we normalize the vector. Thus, we don't need to physically normalize it in the index phase.
In extended RaBitQ, the code is computed by a more complicated algorithm. In the code, we assure that the algorithm still produces correct quantization codes whether or not we normalize the vector physically.
It is worth highlighting that when estimating distances based on the quantization codes, we still explicitly use the formula derived from normalization.

Please let me know if you have any further questions.

The issue is the same as https://github.com/VectorDB-NTU/Extended-RaBitQ/issues/1. 

Let me close this comment here and continue the thread in the other repo.

**Closed** 2024-11-20 02:28 UTC
